version: '3'
services:
  moodle-gateway:
    build: .
    ports:
      - 8081:8081
    environment:
      - MOODLE_URL_DOCKER=${MOODLE_URL_ENV}
      - MOODLE_API_KEY_DOCKER=${MOODLE_API_KEY_ENV}
      - MAGENTO_URL_DOCKER=${MAGENTO_URL_ENV}